[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.12.0"
chess = { path = "../chess" }
clap = { version = "4.3.17", features = ["derive"] }
dioxus = { git = "https://github.com/DioxusLabs/dioxus.git" }
dioxus-logger = { version = "0.4.1", features = ["timestamps"] }
futures = "0.3.28"
futures-util = "0.3.28"
log = "0.4.19"
once_cell = "1.18.0"
serde_json = "1.0.103"
tokio-tungstenite-wasm = "0.1.0"
url = "2.4.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
dioxus-web = { git = "https://github.com/DioxusLabs/dioxus.git" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
dioxus-desktop = { git = "https://github.com/DioxusLabs/dioxus.git" }
