[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
build_common = { path = "../build_common" }

[dependencies]
anyhow = "1.0.72"
async-std = "1.12.0"
auto-deref = { path = "../auto-deref" }
chess = { path = "../chess" }
clap = { version = "4.3.19", features = ["derive"] }
common = { path = "../common" }
dioxus = { git = "https://github.com/DioxusLabs/dioxus.git" }
dioxus-logger = { version = "0.4.1", features = ["timestamps"] }
futures = "0.3.28"
futures-util = "0.3.28"
log = "0.4.19"
once_cell = "1.18.0"
regex = "1.9.3"
serde_json = "1.0.104"
tokio-tungstenite-wasm = "0.1.0"
url = "2.4.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
dioxus-web = { git = "https://github.com/DioxusLabs/dioxus.git" }
dioxus-fullstack = { git = "https://github.com/DioxusLabs/dioxus.git", features = ["web"] }
js-sys = "0.3.64"
server-functions = { path = "../server-functions", features = ["web"] }
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-process = "1.7.0"
dioxus-fullstack = { git = "https://github.com/DioxusLabs/dioxus.git", features = ["desktop"]}
dioxus-desktop = { git = "https://github.com/DioxusLabs/dioxus.git" }
server-functions = { path = "../server-functions", features = ["desktop"] }
tokio-tungstenite = { version = "*", features = ["native-tls"] }
