version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      dev-dependencies: # Name of group that will appear on pull request
        patterns:
          - "*" # A wildcard that matches all dependencies in the package