repos:
-   repo: local
    hooks:
    -   id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt -- --check
        language: system
        files: \.rs$
        types: [file]
    -   id: cargo-check
        name: cargo check
        entry: ./cargo_check_all.sh
        language: script
        files: \.rs$
        types: [file]
