repos:
-   repo: local
    hooks:
    -   id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt -- --check
        language: system
        files: \.rs$
        types: [file]
    -   id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy -- -D warnings
        language: system
        files: \.rs$
        types: [file]
    -   id: cargo-check
        name: cargo check
        entry: cargo check
        language: system
        files: \.rs$
        types: [file]
