[workspace]
resolver = "2"
members = [
    "auto-deref",
    "client",
    "server",
    "chess",
    "common",
    "build_common",
    "server-functions",
]

[profile.release]
codegen-units = 1
lto = "fat"

[build]
rustflags = ["-C", "target-cpu=native"]
