# fly.toml app configuration file generated for muddy-fog-684 on 2023-07-16T15:32:09-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "muddy-fog-684"
primary_region = "dfw"

[build]
  dockerfile = "Dockerfile.fly"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
