[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.19", features = ["ws"] }
clap = { version = "4.3.17", features = ["derive"] }
dioxus = { git = "https://github.com/DioxusLabs/dioxus.git" }
dioxus-fullstack = { git = "https://github.com/DioxusLabs/dioxus.git", features = ["axum"] }
dioxus-logger = { version = "0.4.1", features = ["timestamps"] }
futures = "0.3.28"
log = "0.4.19"
tokio = { version = "1.29.1", features = ["full"] }
tower-http = { version = "0.4.2" }
