[package]
name = "chess-app"
version = "0.1.0"
edition = "2021"

[features]
desktop = ["dioxus-fullstack/desktop"]
web = ["dioxus-fullstack/web"]
server = ["dioxus-fullstack/ssr", "dioxus-fullstack/axum"]

[dependencies]
dioxus = "0.4.0"
dioxus-fullstack = {version = "0.4.1", optional = true }