[package]
name = "chess-app"
version = "0.1.0"
edition = "2021"

# Define features for conditional compilation
[features]
client = []
server = ["client"]

# Common dependencies for all targets
[dependencies]
dioxus-fullstack = "0.4.1"
