[package]
name = "chess-app"
version = "0.1.0"
edition = "2021"

# Define features for conditional compilation
[features]
desktop = []
ssr = []
web = []

# Common dependencies for all targets
[dependencies]
dioxus-fullstack = "0.4.1"

# Dependencies specific to the desktop
[target.'cfg(feature = "desktop")'.dependencies]

# Dependencies specific to the server
[target.'cfg(feature = "server")'.dependencies]

# Dependencies specific to the web
[target.'cfg(feature = "web")'.dependencies]
