name: AI Code Reviewer

on: [pull_request]
jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: fxchen/code-review@v0.4
        with:
          openai-key: ${{ secrets.OPENAI_API_KEY }}
