name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write
  packages: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/oxideops/oxide-chess:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build Server
        run: cargo build --features ssr --release

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Application
        run: flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
