name: Push WASM to Github Page main is updated

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update deployment repo
      run: ./deploy-web.sh
