name: Rust CI

on:
  pull_request:
    branches: [main]

jobs:
  check:

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/event-horizon-technologies/chess:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v3

    - name: Check Formatting
      run: cargo fmt -- --check

    - name: Build WASM
      run: trunk build

    - name: Build Rust
      run: cargo build

    - name: Run Client Tests
      run: cargo test
