name: Rustfmt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-format:
    name: Check code format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          override: true
      - name: Check code format
        run: cargo fmt -- --check
