name: Rust CI

on:
  pull_request:
    branches: [main]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true # This makes the stable toolchain default
        components: rustfmt # This installs rustfmt

    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Cache target
      uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-target-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-target-

    - name: Check Formatting
      run: cargo fmt -- --check

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
