name: Rust CI

on:
  pull_request:
    branches: [main]

jobs:
  check:

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/oxideops/chess:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Check Formatting
      run: cargo fmt -- --check
      
    - name: Build Client
      run: cargo build -p client

    - name: Run Client Tests
      run: cargo test -p client

    - name: Build WASM
      run: trunk build

    - name: Build Server
      run: cargo build -p server

    - name: Run Server Tests
      run: cargo test -p server
