name: Rust CI

on:
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/oxideops/oxide-chess:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Check Formatting
      run: cargo fmt -- --check

    - name: Check Desktop
      run: cargo clippy -F desktop -- -D warnings

    - name: Check Web
      run: cargo clippy -F web -- -D warnings

    - name: Check Server
      run: cargo clippy -F ssr -- -D warnings

    - name: Check Database
      run: cargo clippy -p database -- -D warnings