name: Rust CI

on:
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/oxideops/oxide-chess:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Check Formatting
      run: cargo fmt -- --check
      
    - name: Check Desktop
      run: cargo check --features desktop

    - name: Check Web
      run: cargo check --features web

    - name: Check Server
      run: cargo check --features ssr
